# The Site Configuration

theme: jekyll-theme-chirpy
lang: en
timezone: Asia/Seoul

title: Daily Digest: News You Can Trust
tagline: Curated headlines and stories from around you
description: >-
  Catch up on the latest stories from the world, society, culture, and everyday life. Updated daily.

url: "https://daegweon.github.io"
baseurl: ""

github:
  username: daegweon

twitter:
  username: daegweon

social:
  name: Daegweon Ko
  email: kingkdg@gmail.com
  links:
    - https://github.com/daegweon

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

analytics:
  google:
    id: G-M2Z3M1H9XV

theme_mode:  # [light | dark]

avatar: # optional

social_preview_image: # optional

toc: true

comments:
  provider:
  utterances:
    repo: daegweon/daegweon.github.io
    issue_term:

pwa:
  enabled: true
  cache:
    enabled: true

paginate: 10

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Daegweon Ko
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"
