name: Auto Blog Post to GitHub Pages

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai requests

      - name: Generate post
        run: python generate_post.py
        env:
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          COUPANG_PARTNER_ID: ${{ secrets.COUPANG_PARTNER_ID }}

      - name: 🔍 Debug token
        run: echo "GH_TOKEN is ${{ secrets.GH_TOKEN }}"

      - name: Commit and push with PAT
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
          # ✅ remote URL에 PAT 삽입 (핵심)
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/daegweon/daegweon.github.io.git
      
          git add _posts/
          git commit -m "🤖 Auto-post: $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push origin main




